### ISSUE TITLE
No responding after luanching hypvm.elf in qemu

### ISSUE THREAD

**Issue by lmlaaron** [quic/gunyah-hypervisor#10]
I have built the environment using provided Dockerfile on a Ubuntu 16.04 machine without errors. The image is on dockerhub:  ml2558/gunyah:gunyah. However, when I follow the rest process building the hypervisor, resource manger and c runtime and pack them into single hypvm.elf binary and try to run them using qemu, it does not have any output. Is it normal?

Edit: here is what it looks like:

(gunyah-venv) root@a12fdfadd046:/home/gunyah-hypervisor# qemu-system-aarch64 -machine virt,virtualization=on,gic-version=3,highmem=off \
> -cpu max -m size=2G -smp cpus=8 -nographic \
> -kernel /home/hypvm.elf \
> -device loader,file=$OUTPUT_DIR/Image,addr=$LINUX_BASE \
> -device loader,file=$OUTPUT_DIR/virt.dtb,addr=$DT_BASE \
> -device loader,file=$OUTPUT_DIR/initrd.img,addr=$INITRD_BASE

after entering the above command, the terminal just hangs (no errors, crashes, etc).

**Comment by quic-cvanscha** [comment]
Hi, is your `qemu-system-aarch64 -version` >= 5.0 ?

**Comment by phongt** [comment]
I tried building with gunyah-hyp, c-runtime, resource-manager by "scons platform=qemu featureset=all quality=debug" , run qemu-system-aarch64  got the stuck. 

```
[HYP] Processing package image (0) type=1
[HYP] Elf copied from 0x80400020 to 0x80480000 - size 0xcf4
[HYP] Elf copied from 0x80401020 to 0x80481000 - size 0x43e0
[HYP] Elf copied from 0x80406020 to 0x80486000 - size 0xea0
[HYP] Elf copied from 0x80407020 to 0x80487000 - size 0xe0
[HYP] Processing package image (1) type=2
[HYP] Elf copied from 0x8042a900 to 0x8048d000 - size 0x51b4
[HYP] Elf copied from 0x80430900 to 0x80493000 - size 0x1eb40
[HYP] Elf copied from 0x8044f900 to 0x804b2000 - size 0x260
[HYP] Elf copied from 0x80450900 to 0x804b3000 - size 0x1f4
[HYP] runtime_ipa: 0x80480000
[HYP] app_ipa: 0x8048d000
```
qemu-system-aarch64 -version
QEMU emulator version 5.2.0 (Debian 1:5.2+dfsg-11+deb11u1)
Copyright (c) 2003-2020 Fabrice Bellard and the QEMU Project developers

**Comment by jiayy** [comment]
I build following the docs and it shows the same as phongt , no shell, no vm, no new terminal, Is it normal? How can I interact with the vm ? 

[HYP] Processing package image (0) type=1
[HYP] Elf copied from 0x80400020 to 0x80480000 - size 0xcf4
[HYP] Elf copied from 0x80401020 to 0x80481000 - size 0x43e0
[HYP] Elf copied from 0x80406020 to 0x80486000 - size 0xea0
[HYP] Elf copied from 0x80407020 to 0x80487000 - size 0xe0
[HYP] Processing package image (1) type=2
[HYP] Elf copied from 0x8042a900 to 0x8048d000 - size 0x51b4
[HYP] Elf copied from 0x80430900 to 0x80493000 - size 0x1eb40
[HYP] Elf copied from 0x8044f900 to 0x804b2000 - size 0x260
[HYP] Elf copied from 0x80450900 to 0x804b3000 - size 0x1f4
[HYP] runtime_ipa: 0x80480000
[HYP] app_ipa: 0x8048d000

**Comment by quic-cvanscha** [comment]
Issue appears to be that the following commit was mistakenly not pushed quic/gunyah-c-runtime@16928a7626ee29141c83030b51d196325980924d
Please update gunyah-c-runtime and confirm the issue is resolved.

**Comment by phongt** [comment]
Re-tried and Linux boot up and have console 
```
$ qemu-system-aarch64 -machine virt,virtualization=on,gic-version=3,highmem=off -cpu max -m size=2G -smp cpus=8 -nographic -kernel hypvm.elf -device loader,file=./Image,addr=$LINUX_BASE -device loader,file=./virt.dtb,addr=$DT_BASE -device loader,file=./initrd.img,addr=$INITRD_BASE
[HYP] Processing package image (0) type=1
[HYP] Elf copied from 0x80400020 to 0x80480000 - size 0xcf4
[HYP] Elf copied from 0x80401020 to 0x80481000 - size 0x43e0
[HYP] Elf copied from 0x80406020 to 0x80486000 - size 0xea0
[HYP] Elf copied from 0x80407020 to 0x80487000 - size 0xe0
[HYP] Processing package image (1) type=2
[HYP] Elf copied from 0x80407500 to 0x8048d000 - size 0x51b4
[HYP] Elf copied from 0x8040d500 to 0x80493000 - size 0x1eb40
[HYP] Elf copied from 0x8042c500 to 0x804b2000 - size 0x260
[HYP] Elf copied from 0x8042d500 to 0x804b3000 - size 0x1f4
[HYP] runtime_ipa: 0x80480000
[HYP] app_ipa: 0x8048d000
[RM] Starting Resource Manager, version: 3145bda (Mon Nov 1 12:02:32 2021 UTC)
[RM] memparcel_construct sglist:
[RM]  [0]: me:40a phys:40000000 (20000000)
[RM] memparcel_construct ret=0
[RM] create_dtbo: hyp -1 resmem -1
[RM] create_resmem_nodes: memparcel labelled 0 is the base memory at 0x40000000
[RM] init completed
[RM] UART is disabled
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x380069. RAZ
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x3a0067. RAZ
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x3c0067. RAZ
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x380067. RAZ
[HYP] secondary cpu (1) cold boot
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x380069. RAZ
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x3a0067. RAZ
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x3c0067. RAZ
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x380067. RAZ
[HYP] secondary cpu (2) cold boot
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x380069. RAZ
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x3a0067. RAZ
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x3c0067. RAZ
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x380067. RAZ
[HYP] secondary cpu (3) cold boot
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x380069. RAZ
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x3a0067. RAZ
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x3c0067. RAZ
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x380067. RAZ
[HYP] secondary cpu (4) cold boot
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x380069. RAZ
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x3a0067. RAZ
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x3c0067. RAZ
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x380067. RAZ
[HYP] secondary cpu (5) cold boot
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x380069. RAZ
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x3a0067. RAZ
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x3c0067. RAZ
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x380067. RAZ
[HYP] secondary cpu (6) cold boot
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x380069. RAZ
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x3a0067. RAZ
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x3c0067. RAZ
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x380067. RAZ
[HYP] secondary cpu (7) cold boot
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x380069. RAZ
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x3a0067. RAZ
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x3c0067. RAZ
[HYP] sysreg_read: unhandled TID3 trap, ISS: 0x380067. RAZ
[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x000f0510]
[    0.000000] Linux version 5.15.0-10643-gfe91c4725aee (phongtran@debian) (aarch64-linux-gnu-gcc (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP Sat Nov 6 17:55:18 +07 2021
[    0.000000] Machine model: linux,dummy-virt
[    0.000000] efi: UEFI not found.
[    0.000000] [Firmware Bug]: Kernel image misaligned at boot, please fix your bootloader!
[    0.000000] NUMA: No NUMA configuration found
[    0.000000] NUMA: Faking a node at [mem 0x0000000040000000-0x000000005fffffff]
[    0.000000] NUMA: NODE_DATA [mem 0x5fef3c00-0x5fef5fff]
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000040000000-0x000000005fffffff]
[    0.000000]   DMA32    empty
[    0.000000]   Normal   empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000040000000-0x000000005fffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000040000000-0x000000005fffffff]
[    0.000000] cma: Reserved 32 MiB at 0x000000005d400000
[    0.000000] psci: probing for conduit method from DT.
[    0.000000] psci: PSCIv1.1 detected in firmware.
[    0.000000] psci: Using standard PSCI v0.2 function IDs
[    0.000000] psci: MIGRATE_INFO_TYPE not supported.
[    0.000000] psci: SMC Calling Convention v1.0
[    0.000000] percpu: Embedded 19 pages/cpu s40728 r8192 d28904 u77824
[    0.000000] Detected PIPT I-cache on CPU0
[    0.000000] CPU features: detected: Branch Target Identification
[    0.000000] CPU features: detected: GIC system register CPU interface
[    0.000000] CPU features: detected: Spectre-v2
[    0.000000] CPU features: detected: Spectre-v4
[    0.000000] CPU features: kernel page table isolation forced ON by KASLR
[    0.000000] CPU features: detected: Kernel page table isolation (KPTI)
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 129024
[    0.000000] Policy zone: DMA
[    0.000000] Kernel command line: rw root=/dev/ram rdinit=/sbin/init earlyprintk=serial,ttyAMA0 console=ttyAMA0
[    0.000000] Unknown command line parameters: earlyprintk=serial,ttyAMA0
[    0.000000] Dentry cache hash table entries: 65536 (order: 7, 524288 bytes, linear)
[    0.000000] Inode-cache hash table entries: 32768 (order: 6, 262144 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 444624K/524288K available (16000K kernel code, 3192K rwdata, 8684K rodata, 6528K init, 506K bss, 46896K reserved, 32768K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=8, Nodes=1
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000] rcu: 	RCU event tracing is enabled.
[    0.000000] rcu: 	RCU restricting CPUs from NR_CPUS=256 to nr_cpu_ids=8.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 25 jiffies.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=8
[    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[    0.000000] GICv3: 988 SPIs implemented
[    0.000000] GICv3: 0 Extended SPIs implemented
[    0.000000] GICv3: Distributor has no Range Selector support
[    0.000000] Root IRQ handler: gic_handle_irq
[    0.000000] GICv3: 16 PPIs implemented
[    0.000000] GICv3: CPU0: found redistributor 0 region 0:0x00000000080a0000
[    0.000000] random: get_random_bytes called from start_kernel+0x478/0x664 with crng_init=0
[    0.000000] arch_timer: cp15 timer(s) running at 62.50MHz (virt).
[    0.000000] clocksource: arch_sys_counter: mask: 0x1ffffffffffffff max_cycles: 0x1cd42e208c, max_idle_ns: 881590405314 ns
[    0.000081] sched_clock: 57 bits at 62MHz, resolution 16ns, wraps every 4398046511096ns
[    0.008778] Console: colour dummy device 80x25
[    0.011623] Calibrating delay loop (skipped), value calculated using timer frequency.. 125.00 BogoMIPS (lpj=250000)
[    0.012199] pid_max: default: 32768 minimum: 301
[    0.013087] LSM: Security Framework initializing
[    0.014661] Mount-cache hash table entries: 1024 (order: 1, 8192 bytes, linear)
[    0.014725] Mountpoint-cache hash table entries: 1024 (order: 1, 8192 bytes, linear)
[    0.055231] rcu: Hierarchical SRCU implementation.
[    0.060501] EFI services will not be available.
[    0.064123] smp: Bringing up secondary CPUs ...
[    0.071514] Detected PIPT I-cache on CPU1
[    0.072212] GICv3: CPU1: found redistributor 1 region 0:0x00000000080c0000
[    0.072876] CPU1: Booted secondary processor 0x0000000001 [0x000f0510]
[    0.082520] Detected PIPT I-cache on CPU2
[    0.082799] GICv3: CPU2: found redistributor 2 region 0:0x00000000080e0000
[    0.083466] CPU2: Booted secondary processor 0x0000000002 [0x000f0510]
[    0.088290] Detected PIPT I-cache on CPU3
[    0.088613] GICv3: CPU3: found redistributor 3 region 0:0x0000000008100000
[    0.089612] CPU3: Booted secondary processor 0x0000000003 [0x000f0510]
[    0.097188] Detected PIPT I-cache on CPU4
[    0.097802] GICv3: CPU4: found redistributor 4 region 0:0x0000000008120000
[    0.099284] CPU4: Booted secondary processor 0x0000000004 [0x000f0510]
[    0.105676] Detected PIPT I-cache on CPU5
[    0.106209] GICv3: CPU5: found redistributor 5 region 0:0x0000000008140000
[    0.107404] CPU5: Booted secondary processor 0x0000000005 [0x000f0510]
[    0.114508] Detected PIPT I-cache on CPU6
[    0.114945] GICv3: CPU6: found redistributor 6 region 0:0x0000000008160000
[    0.116032] CPU6: Booted secondary processor 0x0000000006 [0x000f0510]
[    0.123024] Detected PIPT I-cache on CPU7
[    0.123511] GICv3: CPU7: found redistributor 7 region 0:0x0000000008180000
[    0.124705] CPU7: Booted secondary processor 0x0000000007 [0x000f0510]
[    0.126354] smp: Brought up 1 node, 8 CPUs
[    0.126620] SMP: Total of 8 processors activated.
[    0.126789] CPU features: detected: 32-bit EL0 Support
[    0.126905] CPU features: detected: 32-bit EL1 Support
[    0.127046] CPU features: detected: Common not Private translations
[    0.127073] CPU features: detected: CRC32 instructions
[    0.127199] CPU features: detected: RCpc load-acquire (LDAPR)
[    0.127224] CPU features: detected: LSE atomic instructions
[    0.127245] CPU features: detected: Privileged Access Never
[    0.127265] CPU features: detected: Random Number Generator
[    0.127285] CPU features: detected: Speculation barrier (SB)
[    2.156093] CPU: All CPU(s) started at EL1
[    2.163619] alternatives: patching kernel code
[    2.233162] devtmpfs: initialized
[    2.270369] KASLR enabled
[    2.274069] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
[    2.275795] futex hash table entries: 2048 (order: 5, 131072 bytes, linear)
[    2.293242] pinctrl core: initialized pinctrl subsystem
[    2.321890] DMI not present or invalid.
[    2.341142] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    2.374602] DMA: preallocated 128 KiB GFP_KERNEL pool for atomic allocations
[    2.377163] DMA: preallocated 128 KiB GFP_KERNEL|GFP_DMA pool for atomic allocations
[    2.378901] DMA: preallocated 128 KiB GFP_KERNEL|GFP_DMA32 pool for atomic allocations
[    2.379454] audit: initializing netlink subsys (disabled)
[    2.384331] audit: type=2000 audit(2.184:1): state=initialized audit_enabled=0 res=1
[    2.395680] thermal_sys: Registered thermal governor 'step_wise'
[    2.395846] thermal_sys: Registered thermal governor 'power_allocator'
[    2.399031] cpuidle: using governor menu
[    2.401765] hw-breakpoint: found 6 breakpoint and 4 watchpoint registers.
[    2.405716] ASID allocator initialised with 32768 entries
[    2.416529] Serial: AMBA PL011 UART driver
[    2.526512] 9000000.pl011: ttyAMA0 at MMIO 0x9000000 (irq = 49, base_baud = 0) is a PL011 rev1
[    2.596526] printk: console [ttyAMA0] enabled
[    2.674434] HugeTLB registered 1.00 GiB page size, pre-allocated 0 pages
[    2.675749] HugeTLB registered 32.0 MiB page size, pre-allocated 0 pages
[    2.677848] HugeTLB registered 2.00 MiB page size, pre-allocated 0 pages
[    2.678688] HugeTLB registered 64.0 KiB page size, pre-allocated 0 pages
[    2.701178] ACPI: Interpreter disabled.
[    2.716545] iommu: Default domain type: Translated 
[    2.717408] iommu: DMA domain TLB invalidation policy: strict mode 
[    2.720200] vgaarb: loaded
[    2.724484] SCSI subsystem initialized
[    2.730963] usbcore: registered new interface driver usbfs
[    2.732161] usbcore: registered new interface driver hub
[    2.732988] usbcore: registered new device driver usb
[    2.738728] pps_core: LinuxPPS API ver. 1 registered
[    2.739454] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    2.740756] PTP clock support registered
[    2.742344] EDAC MC: Ver: 3.0.0
[    2.755037] FPGA manager framework
[    2.758698] Advanced Linux Sound Architecture Driver Initialized.
[    2.801135] clocksource: Switched to clocksource arch_sys_counter
[    2.805389] VFS: Disk quotas dquot_6.6.0
[    2.806158] VFS: Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[    2.810848] pnp: PnP ACPI: disabled
[    2.874188] NET: Registered PF_INET protocol family
[    2.878167] IP idents hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    2.887127] tcp_listen_portaddr_hash hash table entries: 256 (order: 0, 4096 bytes, linear)
[    2.887880] TCP established hash table entries: 4096 (order: 3, 32768 bytes, linear)
[    2.888683] TCP bind hash table entries: 4096 (order: 4, 65536 bytes, linear)
[    2.889334] TCP: Hash tables configured (established 4096 bind 4096)
[    2.892671] UDP hash table entries: 256 (order: 1, 8192 bytes, linear)
[    2.893323] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes, linear)
[    2.897214] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    2.908179] RPC: Registered named UNIX socket transport module.
[    2.908817] RPC: Registered udp transport module.
[    2.909248] RPC: Registered tcp transport module.
[    2.910146] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    2.911457] PCI: CLS 0 bytes, default 64
[    2.923230] Unpacking initramfs...
[    2.934918] hw perfevents: enabled with armv8_pmuv3 PMU driver, 5 counters available
[    2.941862] kvm [1]: HYP mode not available
[    2.951815] Initialise system trusted keyrings
[    2.955790] workingset: timestamp_bits=42 max_order=17 bucket_order=0
[    3.004618] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    3.014354] NFS: Registering the id_resolver key type
[    3.016942] Key type id_resolver registered
[    3.018202] Key type id_legacy registered
[    3.020973] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    3.024694] nfs4flexfilelayout_init: NFSv4 Flexfile Layout Driver Registering...
[    3.029118] 9p: Installing v9fs 9p2000 file system support
[    3.105840] Key type asymmetric registered
[    3.106836] Asymmetric key parser 'x509' registered
[    3.108745] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 245)
[    3.109758] io scheduler mq-deadline registered
[    3.110331] io scheduler kyber registered
[    3.156680] Freeing initrd memory: 1104K
[    3.223528] pl061_gpio 9030000.pl061: PL061 GPIO chip registered
[    3.263130] pci-host-generic 3f000000.pcie: host bridge /pcie@10000000 ranges:
[    3.267256] pci-host-generic 3f000000.pcie:       IO 0x003eff0000..0x003effffff -> 0x0000000000
[    3.271429] pci-host-generic 3f000000.pcie:      MEM 0x0010000000..0x003efeffff -> 0x0010000000
[    3.276457] pci-host-generic 3f000000.pcie: ECAM at [mem 0x3f000000-0x3fffffff] for [bus 00-0f]
[    3.292887] pci-host-generic 3f000000.pcie: PCI host bridge to bus 0000:00
[    3.296028] pci_bus 0000:00: root bus resource [bus 00-0f]
[    3.297737] pci_bus 0000:00: root bus resource [io  0x0000-0xffff]
[    3.299954] pci_bus 0000:00: root bus resource [mem 0x10000000-0x3efeffff]
[    3.305514] pci 0000:00:00.0: [1b36:0008] type 00 class 0x060000
[    3.327257] pci 0000:00:01.0: [1af4:1000] type 00 class 0x020000
[    3.329524] pci 0000:00:01.0: reg 0x10: [io  0x0000-0x001f]
[    3.331669] pci 0000:00:01.0: reg 0x20: [mem 0x00000000-0x00003fff 64bit pref]
[    3.333829] pci 0000:00:01.0: reg 0x30: [mem 0x00000000-0x0003ffff pref]
[    3.343089] pci 0000:00:01.0: BAR 6: assigned [mem 0x10000000-0x1003ffff pref]
[    3.355907] pci 0000:00:01.0: BAR 4: assigned [mem 0x10040000-0x10043fff 64bit pref]
[    3.359297] pci 0000:00:01.0: BAR 0: assigned [io  0x1000-0x101f]
[    3.393616] EINJ: ACPI disabled.
[    3.545822] virtio-pci 0000:00:01.0: enabling device (0000 -> 0003)
[    3.603699] Serial: 8250/16550 driver, 4 ports, IRQ sharing enabled
[    3.623848] SuperH (H)SCI(F) driver initialized
[    3.628395] msm_serial: driver initialized
[    3.643442] cacheinfo: Unable to detect cache hierarchy for CPU 0
[    3.697347] loop: module loaded
[    3.706068] megasas: 07.719.03.00-rc1
[    3.728238] physmap-flash 0.flash: physmap platform flash device: [mem 0x00000000-0x03ffffff]
[    3.743169] 0.flash: Found 2 x16 devices at 0x0 in 32-bit bank. Manufacturer ID 0x000000 Chip ID 0x000000
[    3.745169] Intel/Sharp Extended Query Table at 0x0031
[    3.747541] Using buffer write method
[    3.749230] physmap-flash 0.flash: physmap platform flash device: [mem 0x04000000-0x07ffffff]
[    3.751420] 0.flash: Found 2 x16 devices at 0x0 in 32-bit bank. Manufacturer ID 0x000000 Chip ID 0x000000
[    3.752404] Intel/Sharp Extended Query Table at 0x0031
[    3.753704] Using buffer write method
[    3.754868] Concatenating MTD devices:
[    3.755292] (0): "0.flash"
[    3.755587] (1): "0.flash"
[    3.755851] into device "0.flash"
[    3.924212] SPI driver mtd_dataflash has no spi_device_id for atmel,at45
[    3.926039] SPI driver mtd_dataflash has no spi_device_id for atmel,dataflash
[    3.954282] libphy: Fixed MDIO Bus: probed
[    3.971913] tun: Universal TUN/TAP device driver, 1.6
[    4.015580] thunder_xcv, ver 1.0
[    4.016978] thunder_bgx, ver 1.0
[    4.018261] nicpf, ver 1.0
[    4.029092] hclge is initializing
[    4.030331] hns3: Hisilicon Ethernet Network Driver for Hip08 Family - version
[    4.031223] hns3: Copyright (c) 2017 Huawei Corporation.
[    4.032713] e1000: Intel(R) PRO/1000 Network Driver
[    4.033145] e1000: Copyright (c) 1999-2006 Intel Corporation.
[    4.033885] e1000e: Intel(R) PRO/1000 Network Driver
[    4.034290] e1000e: Copyright(c) 1999 - 2015 Intel Corporation.
[    4.034998] igb: Intel(R) Gigabit Ethernet Network Driver
[    4.035441] igb: Copyright (c) 2007-2014 Intel Corporation.
[    4.036072] igbvf: Intel(R) Gigabit Virtual Function Network Driver
[    4.036562] igbvf: Copyright (c) 2009 - 2012 Intel Corporation.
[    4.039201] sky2: driver version 1.30
[    4.053137] VFIO - User Level meta-driver version: 0.3
[    4.070314] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    4.072002] ehci-pci: EHCI PCI platform driver
[    4.073227] ehci-platform: EHCI generic platform driver
[    4.085715] ehci-orion: EHCI orion driver
[    4.087105] ehci-exynos: EHCI Exynos driver
[    4.088450] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    4.091765] ohci-pci: OHCI PCI platform driver
[    4.093007] ohci-platform: OHCI generic platform driver
[    4.094741] ohci-exynos: OHCI Exynos driver
[    4.099622] usbcore: registered new interface driver usb-storage
[    4.127132] rtc-pl031 9010000.pl031: registered as rtc0
[    4.129227] rtc-pl031 9010000.pl031: setting system clock to 2021-11-17T15:09:38 UTC (1637161778)
[    4.137031] i2c_dev: i2c /dev entries driver
[    4.183082] sdhci: Secure Digital Host Controller Interface driver
[    4.183788] sdhci: Copyright(c) Pierre Ossman
[    4.187789] SPI driver mmc_spi has no spi_device_id for mmc-spi-slot
[    4.190233] Synopsys Designware Multimedia Card Interface Driver
[    4.198277] sdhci-pltfm: SDHCI platform and OF driver helper
[    4.221196] ledtrig-cpu: registered to indicate activity on CPUs
[    4.236482] usbcore: registered new interface driver usbhid
[    4.237133] usbhid: USB HID core driver
[    4.283716] NET: Registered PF_PACKET protocol family
[    4.287381] 9pnet: Installing 9P2000 support
[    4.288659] Key type dns_resolver registered
[    4.291736] Loading compiled-in X.509 certificates
[    4.387295] input: gpio-keys as /devices/platform/gpio-keys/input/input0
[    4.399137] ALSA device list:
[    4.399627]   No soundcards found.
[    4.410262] uart-pl011 9000000.pl011: no DMA platform data
[    4.537621] Freeing unused kernel memory: 6528K
[    4.549913] Run /sbin/init as init process

Please press Enter to activate this console. 
/ # 
/ # uname  -a
Linux (none) 5.15.0-10643-gfe91c4725aee #1 SMP Sat Nov 6 17:55:18 +07 2021 aarch64 GNU/Linux
/ # arch
aarch64
/ # 


```

**Comment by quic-cvanscha** [comment]
Great, thanks for the confirmation!

**Comment by xrivendell7** [comment]
Hi, cvanscha. I'm sure i update the commit of gunyah-c-runtime, all the things it build in provided DockerFile. Howerver, I still hang in the same place.
```bash
(gunyah-venv) # ./start_cmd.sh hypvm.elf
[HYP] Processing package image (0) type=1
[HYP] Elf copied from 0x80400020 to 0x80480000 - size 0xce4
[HYP] Elf copied from 0x80401020 to 0x80481000 - size 0x43e0
[HYP] Elf copied from 0x80406020 to 0x80486000 - size 0xe90
[HYP] Elf copied from 0x80407020 to 0x80487000 - size 0xe0
[HYP] Processing package image (1) type=2
[HYP] Elf copied from 0x8042a3e0 to 0x8048d000 - size 0x5204
[HYP] Elf copied from 0x804303e0 to 0x80493000 - size 0x1f37c
[HYP] Elf copied from 0x804503e0 to 0x804b3000 - size 0x258
[HYP] Elf copied from 0x804513e0 to 0x804b4000 - size 0x1f4
[HYP] runtime_ipa: 0x80480000
[HYP] app_ipa: 0x8048d000
```
and my qemu and gunyah-c-runtime
```bash
(gunyah-venv) # qemu-system-aarch64 --version
QEMU emulator version 6.1.50 (v6.1.0-2192-g18e356a53a)
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers
(gunyah-venv) # pwd
/usr/local/src/gunyah-c-runtime/include
(gunyah-venv) # head guest_types.h
// Automatically generated. Do not modify.
//
// © 2021 Qualcomm Innovation Center, Inc. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause

#include <stdalign.h>
#include <stdatomic.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
(gunyah-venv) # pwd
/usr/local/src/gunyah-c-runtime/include
(gunyah-venv) # sed -n '70,80p' guest_types.h
        vmaddr_t              device_me_base;
        vmaddr_t              entry_hlos;
        vmaddr_t              hlos_vm_base;
        size_t                hlos_vm_size;
        vmaddr_t              hlos_dt_base;
        vmaddr_t              hlos_ramfs_base;
        cap_id_t              uart_me_capid;
        paddr_t               uart_address;
        cap_id_t              partition_capid;
        cap_id_t              cspace_capid;
        cap_id_t              vcpu_capid;
```
